### ISSUE TITLE
`Rc::adopt` requires both `T`s to be the same

### ISSUE THREAD

**Issue by LoganDark** [artichoke/cactusref#96]
Say I'm making a structure that contains something else - this does not work:

```rs
impl Container{
	fn new(contained: Rc<Contained>) -> Rc<Self> {
		let new = Rc::new(Self { contained });
		unsafe { Rc::adopt(&new, &new.contained) };
		new
	}
}
```

That's because `Rc::adopt` requires both `T`s to be the same. Is this intended? I looked at the linked list example, and it looks like it's calling adopt like `Rc::adopt(&parent, &child)` for every `Rc<Node<T>>` that contains an `Rc<Node<T>>`, and that only works because `Node<T>` is itself.

**Comment by lopopolo** [comment]
Hi @LoganDark, it is intentional that `Rc::adopt` requires both `Rc`s to have the same inner `T`.

`cactusref::Rc` is meant to be used in situations where `T` has `Rc<T>` fields. I'm not sure how `Container` and `Contained` are defined, but without this self-contained relationship on `T`, I'm not sure if the cycle detection and cycle breaking `drop` in `cactusref` are required for what you're trying to do. From the looks of things, I think `std::rc::Rc` is more appropriate for your use case.

**Comment by LoganDark** [comment]
> Hi @LoganDark, it is intentional that `Rc::adopt` requires both `Rc`s to have the same inner `T`.
> 
> `cactusref::Rc` is meant to be used in situations where `T` has `Rc<T>` fields. I'm not sure how `Container` and `Contained` are defined, but without this self-contained relationship on `T`, I'm not sure if the cycle detection and cycle breaking `drop` in `cactusref` are required for what you're trying to do. From the looks of things, I think `std::rc::Rc` is more appropriate for your use case.

I can't go into exact detail on what I'm doing (mostly because I'm not sure yet), but basically things like hash sets and etc can contain other objects that may not themselves be hash sets, but end up transitively creating a cycle for whatever reason. Right now cactusref seems to expect me to somehow adopt through multiple levels of indirection if I want to do this, which is not feasible (and also probably not semantically correct).

(For example, Lua has tables which have metatables which are fine, but Lua also contains userdata that can also have metatables, so the userdata would have to adopt the table, which is currently impossible. Therefore cactusref does not allow for an implementation of Lua.)

Of course the documentation and lack of recent activity suggest that cactusref is abandoned and not suitable for use anymore but I haven't gotten any confirmation one way or the other and cactusref is the only crate of its type so I'm trying to be optimistic here. :)

Why is it not possible for any Rc to adopt any other Rc as a field? The limitation seems quite arbitrary.

**Comment by lopopolo** [comment]
> Why is it not possible for any Rc to adopt any other Rc as a field? The limitation seems quite arbitrary.

CactusRef's cycle-detecting `Drop` implementation boils down to creating a directed graph of adoptions. That graph is implemented by storing pointers to the `Rc`'s inner `RcBox<T>`:

https://github.com/artichoke/cactusref/blob/1fac53574c537279cdcdd0c1aebc87e7fc433ad5/src/link.rs#L90-L93

`Drop` requires this graph to contain `T` so `T` can have a `Layout` computed so it can be deallocated in several places, like this one:

https://github.com/artichoke/cactusref/blob/1fac53574c537279cdcdd0c1aebc87e7fc433ad5/src/drop.rs#L206-L211

I am not sure how reasonable it is for this `ptr` field to be type erased. In the absence of type erasure, I'm not sure how that graph could be constructed given the number and layout of all of the `T`s are not known to the library.

> (For example, Lua has tables which have metatables which are fine, but Lua also contains userdata that can also have metatables, so the userdata would have to adopt the table, which is currently impossible. Therefore cactusref does not allow for an implementation of Lua.)

The thing I had in mind when designing CactusRef was a Ruby `RValue`. An `RValue` is itself boxed (it can contain a `f64` or an `i64` or a `Hash` or a `Regexp`, etc.). `RValue`s can also have instance variables which themselves are `RValue`s and can form cycles.

`RValue`s have the property where no item other than the interpreter is the true owner of the graph. Is that true in the Lua case?

Would it be more appropriate for the things in user data to use a `std::rc::Weak` since the metatables are truly owned by the Lua interpreter? I'd expect the Lua interpreter to be responsible for dropping the metatables at which point you would not expect the `Weak`s in user data to be upgradable anyway.

**Comment by lopopolo** [comment]
> Of course the documentation and lack of recent activity suggest that cactusref is abandoned and not suitable for use anymore but I haven't gotten any confirmation one way or the other and cactusref is the only crate of its type so I'm trying to be optimistic here. :)

For context, CactusRef was initially developed as an experiment in 2019. This repository was archived for about 2 years until spring 2021 where I was motivated to get the library to a publishable but still very experimental state by a tweet[^1] from @.pcwalton.

Since then I haven't invested in this crate. Maybe I should archive the repository again.

[^1]: https://twitter.com/pcwalton/status/1376594932597616641

**Comment by LoganDark** [comment]
> The thing I had in mind when designing CactusRef was a Ruby `RValue`. An `RValue` is itself boxed (it can contain a `f64` or an `i64` or a `Hash` or a `Regexp`, etc.). `RValue`s can also have instance variables which themselves are `RValue`s and can form cycles.

But it wouldn't make sense for a userdata's metatable to be a generic value that could be a number or a boolean. That's something that I should be able to forbid on the type level by using a table directly. 

> `RValue`s have the property where no item other than the interpreter is the true owner of the graph. Is that true in the Lua case?

In current (non-Rust) implementations, yes. Whenever native code needs to keep a reference to a Lua value alive, it stuffs it in the registry, which is a globally-accessible root held by the interpreter. That way, the garbage collector (which is usually stop-the-world, BTW) never has to account for references held in a native function's stack.

A Rust implementation would probably use futures for native functions and RAII rather than "put it in the registry and hope it works". And keep in mind that Lua is only an example.

> Maybe I should archive the repository again.

Do you know any other crates that offer similar functionality (no global runtime, deterministic cycle removal) in a more usable state? `shredder` is unusable because it has only one global runtime and can only be used from the main thread, all the other Rust garbage collectors that I know of are stop-the-world.

**Comment by lopopolo** [comment]
In the absence of some concrete asks on what the API gaps are in CactusRef, I can only guess what changes to this library might be helpful to you.

One thing that might make CactusRef work for you is using `cactusref::Rc<dyn Marker>` and asking users of these types to downcast to the concrete types they are stuffing in the registry. Combined with type privacy, this could make for a safer registry API where you can ensure that your types are not swapped out from under you by something else.

Unfortunately, per https://docs.rs/cactusref/0.1.1/cactusref/#cactusref-vs-stdrc, CactusRef does not implement the traits required to store `dyn T` directly. If you were willing to pay the cost of an additional indirection, you might be able to get away with `cactusref::Rc<Box<dyn T>>`. I'd love to accept a PR to support unsized types in a `cactusref::Rc`.

> Of course the documentation and lack of recent activity suggest that cactusref is abandoned and not suitable [...]

Tests run every week on the latest nightly and I have been making small updates to this crate as clippy and nightly changes require. I consider this crate and repository passively maintained. Since I don't have immediate plans to use this code, I am not planning on investing energy here as this is only one of many crates in the Artichoke project.

If you think CactusRef solves one of your needs, that's awesome. If it doesn't quite work and you'd like to contribute code here via PRs, that's also great and I'll try my best to accept patches and push releases.

**Comment by lopopolo** [comment]
@LoganDark I hope this conversation has given you a better idea of the intended use cases for CactusRef. Good luck with what you're building.
